driver: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

settings:
  parallel: true

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[mongodb-mms-agent::default]
      - recipe[mongodb-mms-agent::backup]
